### ISSUE TITLE
License questions

### ISSUE THREAD

**Issue by zzz0072** [debian-lxqt/lxde-qt#3]
There are some license issue in my previous packing at STAGE1 listed below:
* Problem description
   * According AUTHORS in tarball, those packages uses GPL-2 and LGPL-2.1+, and there will be license full text in COPYING
   * COPYING only has LGPL-2.1+ full text. No GPL-2 full text found.

* Packages:
    * compton-conf-0.1.0
    * lxqt-config-randr-0.7.0
    * libqtxdg-0.5.3
    * cmanfm-qt-0.7.0

**Comment by agaida** [comment]
license issues for LXQt are done so far
